# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "475273c59299058d71de9594e91f33da"
name = "tanoti-whatsapp-v2"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders-create"
  topics = [ "orders/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders-fulfilled"
  topics = [ "orders/fulfilled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders-cancelled"
  topics = [ "orders/cancelled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,read_customers"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
